config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :suppliers
  resources :restaurants
  resources :wines

  resources :purchasing_requests do
    resources :purchasing_request_items, only: [:create, :update, :destroy]
    collection do
      get :filter_wines
    end

    member do
      put :approve
      post :approve_notification
      put :reject
      post :reject_notification
      put :request_more_info
      post :request_more_info_notification
      post :create_note
      put :delivered
      post :delivered_notification
    end
  end

  resources :storage_locations do
    resources :items, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :wines
  resources :locations do
    collection do
      get :map
    end
  end

  resources :notifications, only: [:index]

  resources :notes
end

app/models/storage_location.rb
class StorageLocation < ApplicationRecord
  belongs_to :restaurant
  validates :name, :address, :capacity, :temperature, :restaurant, presence: true

  TEMPERATURES = %w[Cold Chill Room]
end

app/controllers/storage_locations_controller.rb
class StorageLocationsController < ApplicationController
  before_action :set_storage_location, only: [:show, :edit, :update, :destroy]

  def index
    @storage_locations = StorageLocation.all
  end

  def show
  end

  def new
    @storage_location = StorageLocation.new
  end

  def edit
  end

  def create
    @storage_location = StorageLocation.new(storage_location_params)

    if @storage_location.save
      redirect_to storage_locations_path, notice: 'Storage location was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @storage_location.update(storage_location_params)
      redirect_to @storage_location, notice: 'Storage location was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @storage_location.destroy
    redirect_to storage_locations_url, notice: 'Storage location was successfully destroyed.'
  end

  private

  def set_storage_location
    @storage_location = StorageLocation.find(params[:id])
  end

  def storage_location_params
    params.require(:storage_location).permit(:name, :address, :capacity, :temperature, :restaurant_id)
  end
end

app/views/storage_locations/edit.html.erb
<div class="container">
  <h1>Edit Storage Location</h1>

  <%= form_with(model: @storage_location, local: true) do |form| %>
    <% if @storage_location.errors.any? %>
      <div class="alert alert-warning">
        <ul>
          <% @storage_location.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :capacity %>
      <%= form.number_field :capacity, class: "form-control", required: true, min: 0 %>
    </div>

    <div class="form-group">
      <%= form.label :temperature %>
      <%= form.select :temperature, ["Frozen", "Refrigerated", "Room temperature"], {}, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :restaurant_id %>
      <%= form.collection_select(:restaurant_id, Restaurant.all, :id, :name, {prompt: "Select a Restaurant"}, {class: "form-control", required: true}) %>
    </div>

    <div class="form-group">
      <%= link_to "Add New Restaurant", new_restaurant_path, class: "btn btn-outline-primary" %>
    </div>

    <div class="form-group">
      <%= form.submit "Update Storage Location", class: "btn btn-primary" %>
      <%= link_to "Cancel", storage_locations_path, class: "btn btn-link" %>
    </div>
  <% end %>
</div>

app/views/storage_locations/index.html.erb
<body class="bg-color">
  <div class="container main-box mt-3">
    <div class="row col-12">
      <h1 class="col-10">Storages</h1>
      <%= link_to "New Storage", new_location_path, class: "btn-create col-2 mb-3 mt-3" %>
    </div><div class="container">
  <h1 class="text-center mb-4"></h1>
  <div class="row justify-content-center">
    <div class="col-12">
      <table class="table container txt-s">
        <thead class="table-title py-3">
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Cap.</th>
            <th>T°</th>
            <th>Restaurant</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @storage_locations.each do |storage_location| %>
            <tr>
              <td><%= storage_location.name %></td>
              <td><%= storage_location.address %></td>
              <td><%= storage_location.capacity %></td>
              <td><%= storage_location.temperature %></td>
              <td><%= storage_location.restaurant.name %></td>
              <td>
              <%= link_to "", storage_location_path(storage_location), class: "fas fa-search me-3" %>
              <%= link_to "", edit_storage_location_path(storage_location), class: "fas fa-edit me-3" %>
              <%= link_to "", storage_location_path(storage_location), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this storage?" }, class: "fas fa-trash-alt" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</body>
<body>

app/views/storage_locations/new.html.erb
<body class="bg-color">
  <div class="container">
    <div class="row">
      <div class="row mt-4">
        <h2 class="col-11">New storage</h2>
        <div class="col-1 align-self-center">
        <%= link_to "", restaurants_path, class: "fas fa-arrow-left me-3" %>
        </div>
        <div class="container main-box col-12">
        <h5 class="border-bottom"><strong>Storage informations</strong></h5>
          <%= form_for @storage_location do |f| %>
          <div class="row col-12">
            <div class="form-group col-6">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control', required: true %>
            </div>
            <div class="form-group col-6">
              <%= f.label :address %>
              <%= f.text_field :address, class: 'form-control', required: true %>
            </div>
          </div>

          <div class="row col-12">
            <div class="form-group col-4">
              <%= f.label :restaurant_id %>
              <%= f.collection_select(:restaurant_id, Restaurant.all, :id, :name, {prompt: "Select a Restaurant"}, {class: "form-select", required: true}) %>
            </div>

            <div class="form-group col-4">
              <%= f.label :capacity %>
              <%= f.email_field :capacity, class: 'form-control', required: true %>
            </div>

            <div class="form-group col-4">
              <%= f.label :temperature %>
              <%= f.select :temperature, StorageLocation::TEMPERATURES,  { class: "form-select" }, required: true %>
            </div>
          </div>
        </div>

          <%= f.submit 'Create', class: 'btn-home col-12 mb-3' %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/storage_locations/show.html.erb
<body class="bg-color">
  <div class="container ">
    <div class="row mt-4">
      <h2 class="col-10"><strong><%= @storage_location.name %></strong> (<%= @storage_location.restaurant.name %>)</h2>
      <div class="col-2 align-self-center">
        <%= link_to "", restaurants_path, class: "fas fa-arrow-left me-3" %>
        <%= link_to "", edit_storage_location_path(@storage_location), class: "fas fa-edit me-3" %>
        <%= link_to "", storage_location_path(@storage_location), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this storage location?" }, class: "fas fa-trash-alt" %>
      </div>

      <div class="container main-box col-12">
        <div class="row mb-3">
          <div class="col-2">Address:</div>
          <div class="col-10"><%= @storage_location.address %></div>
        </div>
        <div class="row mb-3">
          <div class="col-2">Capacity:</div>
          <div class="col-10"><%= @storage_location.capacity %> bottles</div>
        </div>
        <div class="row mb-3">
          <div class="col-2">Temperature:</div>
          <div class="col-10"><%= @storage_location.temperature %></div>
        </div>
      </div>
    </div>
  </div>
</body>