config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :suppliers
  resources :restaurants
  resources :wines

  resources :purchasing_requests do
    resources :purchasing_request_items, only: [:create, :update, :destroy]
    collection do
      get :filter_wines
    end

    member do
      put :approve
      post :approve_notification
      put :reject
      post :reject_notification
      put :request_more_info
      post :request_more_info_notification
      post :create_note
      put :delivered
      post :delivered_notification
    end
  end

  resources :storage_locations do
    resources :items, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :wines
  resources :locations do
    collection do
      get :map
    end
  end

  resources :notifications, only: [:index]

  resources :notes
end

app/views/pages/_info_window.html.erb
<h6><%= link_to wine.maker, wine_path(wine) %></h6>
<p><%= wine.appellation %></p>

app/views/pages/_marker.html.erb
<div class="map-container fs-6">
  <%= link_to wine.maker, wine_path(wine), class: "map-badge" %>
  <%= image_tag "icon_map_pin.png", height: 50, width: 50, alt: "Pin" %>
</div>

app/views/pages/home.html.erb
<body class="bg-img">
  <div class="container mt-4">
    <div class="row">
      <div class="col-6 pt-2 mb-1">
        <div class="card-home">
            <h3><i class="fa fa-archive" aria-hidden="true"></i> STOCK</h3>
          <div class="row col-12">
            <div class="col-6"><%= link_to "CURRENT STOCK", wines_path, class: "btn-main-left" %></div>
            <div class="col-6"><%= link_to "+ NEW WINE", new_wine_path, class: "btn-main-right" %></div>
          </div>
        </div>
      </div>
      <div class="col-6 pt-2 mb-1">
        <div class="card-home">
            <h3><i class="fa fa-shopping-cart" aria-hidden="true"></i> PURCHASING REQUESTS</h3>
          <div class="row col-12">
            <div class="col-6"><%= link_to "CURRENT PR", purchasing_requests_path, class: "btn-main-left" %></div>
            <div class="col-6"><%= link_to "+ NEW PR", new_purchasing_request_path, class: "btn-main-right" %></div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-6 pt-2 mb-1">
        <div class="card-home">
            <h3><i class="fa fa-truck" aria-hidden="true"></i> SUPPLIERS</h3>
          <div class="row col-12">
            <div class="col-6"><%= link_to "ALL SUPPLIERS", suppliers_path, class: "btn-main-left" %></div>
            <div class="col-6"><%= link_to "+ NEW SUPPLIER", new_supplier_path, class: "btn-main-right" %></div>
          </div>
        </div>
      </div>
      <div class="col-6 pt-2 mb-1">
        <div class="card-home">
            <h3><i class="fa fa-map-marker" aria-hidden="true"></i> RESTAURANTS</h3>
          <div class="row col-12">
            <div class="col-6"><%= link_to "ALL RESTAURANTS", restaurants_path, class: "btn-main-left" %></div>
            <div class="col-6"><%= link_to "+ NEW RESTAURANT", new_restaurant_path, class: "btn-main-right" %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container main-box mt-5 col-10">
    <div style="width: 100%; height: 300px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</body>