config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :suppliers
  resources :restaurants
  resources :wines

  resources :purchasing_requests do
    resources :purchasing_request_items, only: [:create, :update, :destroy]
    collection do
      get :filter_wines
    end

    member do
      put :approve
      post :approve_notification
      put :reject
      post :reject_notification
      put :request_more_info
      post :request_more_info_notification
      post :create_note
      put :delivered
      post :delivered_notification
    end
  end

  resources :storage_locations do
    resources :items, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :wines
  resources :locations do
    collection do
      get :map
    end
  end

  resources :notifications, only: [:index]

  resources :notes
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :wines, dependent: :destroy
  has_many :storage_locations, dependent: :destroy
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path, notice: 'Restaurant was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number)
  end
end

app/views/restaurants/edit.html.erb
<body class="bg-color">
  <div class="container">
    <div class="row">
      <div class="row mt-4">
        <h2 class="col-11"><i class="fa fa-edit" aria-hidden="true"></i> <%= @restaurant.name %></h2>
        <div class="col-1 align-self-center">
        <%= link_to "", restaurants_path, class: "fas fa-arrow-left me-3" %>
        </div>
        <div class="container main-box col-12">
        <h5 class="border-bottom"><strong>Restaurant informations</strong></h5>
          <%= form_for @restaurant do |f| %>
          <div class="row col-12">
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control', required: true %>
            </div>
        </div>

          <div class="row col-12">
            <div class="form-group col-6">
              <%= f.label :address %>
              <%= f.text_field :address, class: 'form-control', required: true %>
            </div>

            <div class="form-group col-6">
              <%= f.label :phone_number %>
              <%= f.email_field :phone_number, class: 'form-control', required: true %>
            </div>
          </div>
        </div>

          <%= f.submit 'Update Restaurant', class: 'btn-home col-12 mb-3' %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/restaurants/index.html.erb
<body class="bg-color">
  <div class="container main-box mt-3">
    <div class="row col-12">
      <h1 class="col-10">Restaurants</h1>
      <%= link_to "New restaurant", new_restaurant_path, class: "btn-create col-2 mb-3 mt-3" %>
    </div>
    <div class="container">
      <h1 class="text-center mb-4"></h1>
      <div class="row justify-content-center">
        <div class="col-12">
          <table class="table container txt-s">
            <thead class="table-title py-3">
              <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @restaurants.each do |restaurant| %>
                <tr>
                  <td><%= restaurant.name %></td>
                  <td><%= restaurant.address %></td>
                  <td><%= phone_to restaurant.phone_number, class: "link_to" %></td>
                  <td>
                    <%= link_to "", restaurant, class: "fas fa-search me-3" %>
                    <%= link_to "", edit_restaurant_path(restaurant), class: "fas fa-edit me-3" %>
                    <%= link_to "", restaurant_path(restaurant), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this restaurant?" }, class: "fas fa-trash-alt" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </body>
    </div>
  </div>
<body>

app/views/restaurants/new.html.erb
<body class="bg-color">
  <div class="container">
    <div class="row">
      <div class="row mt-4">
        <h2 class="col-11">New restaurant</h2>
        <div class="col-1 align-self-center">
        <%= link_to "", restaurants_path, class: "fas fa-arrow-left me-3" %>
        </div>
        <div class="container main-box col-12">
        <h5 class="border-bottom"><strong>Restaurant informations</strong></h5>
          <%= form_for @restaurant do |f| %>
          <div class="row col-12">
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control', required: true %>
            </div>
        </div>

          <div class="row col-12">
            <div class="form-group col-6">
              <%= f.label :address %>
              <%= f.text_field :address, class: 'form-control', required: true %>
            </div>

            <div class="form-group col-6">
              <%= f.label :phone_number %>
              <%= f.email_field :phone_number, class: 'form-control', required: true %>
            </div>
          </div>
        </div>

          <%= f.submit 'Create', class: 'btn-home col-12 mb-3' %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/restaurants/show.html.erb
<body class="bg-img">
  <div class="container ">
    <div class="row mt-4">
      <h2 class="col-10"><%= @restaurant.name %></h2>
      <div class="col-2 align-self-center">
        <%= link_to "", restaurants_path, class: "fas fa-arrow-left me-3" %>
        <%= link_to "", edit_restaurant_path(@restaurant), class: "fas fa-edit me-3" %>
        <%= link_to "", restaurant_path(@restaurant), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this restaurant?" }, class: "fas fa-trash-alt" %>
      </div>

      <div class="container main-box col-12">
        <div class="row mb-3">
          <div class="col-2">Phone Number:</div>
          <div class="col-8"><%= phone_to @restaurant.phone_number, class: "link_to" %></div>
          <div class="col-2"><%= link_to "New storage", new_storage_location_path, class: "btn-create col-2 mb-3 mt-3" %></div>
        </div>

        <div class="row mb-3">
          <div class="col-2">Address:</div>
          <div class="col-10"><%= @restaurant.address %></div>
        </div>

        <div class="row mb-3">
          <div class="col-2">Total Capacity:</div>
          <div class="col-10"><%= @restaurant.storage_locations.inject(0) { |sum, storage| sum + storage.capacity } %></div>
        </div>

      <div class="container col-1">
      </div>

      <div class="container main-box col-12">
      <h5>Storage list</h5>
        <div class="row justify-content-center">
          <div class="col-12">
          <table class="table container txt-s">
            <thead class="table-title py-3">
              <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Cap.</th>
                <th>T°</th>
                <th></th>
              </tr>
            </thead>
            <tr>
            <% @restaurant.storage_locations.each do |storage| %>
            <tr>
              <td><%= storage.name %></td>
              <td><%= storage.address %></td>
              <td><%= storage.capacity %></td>
              <td><%= storage.temperature %></td>
              <td>
              <%= link_to "", storage_location_path(storage), class: "fas fa-search me-3" %>
              <%= link_to "", edit_storage_location_path(storage), class: "fas fa-edit me-3" %>
              <%= link_to "", storage_location_path(storage), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this storage?" }, class: "fas fa-trash-alt" %>
              </td>
            <% end %>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>