config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :suppliers
  resources :restaurants
  resources :wines

  resources :purchasing_requests do
    resources :purchasing_request_items, only: [:create, :update, :destroy]
    collection do
      get :filter_wines
    end

    member do
      put :approve
      post :approve_notification
      put :reject
      post :reject_notification
      put :request_more_info
      post :request_more_info_notification
      post :create_note
      put :delivered
      post :delivered_notification
    end
  end

  resources :storage_locations do
    resources :items, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :wines
  resources :locations do
    collection do
      get :map
    end
  end

  resources :notifications, only: [:index]

  resources :notes
end

app/models/purchasing_request.rb
class PurchasingRequest < ApplicationRecord
  include PgSearch::Model

  APPROVAL_STATUSES = %w[pending approved rejected infos_requested delivered].freeze
  before_save :default_values
  validates :approval_status, inclusion: { in: APPROVAL_STATUSES }
  belongs_to :user
  belongs_to :supplier
  validates :user, presence: true
  validates :supplier, presence: true
  has_many :purchasing_request_items, dependent: :destroy
  has_many :items, through: :purchasing_request_items
  has_many :wines, through: :purchasing_request_items
  accepts_nested_attributes_for :purchasing_request_items
  validates :supplier_id, presence: true
  has_many :notes, dependent: :destroy
  # belongs_to :wine

  TIME_SLOTS = [
    ['8:00 AM - 10:00 AM', '8:00-10:00'],
    ['10:00 AM - 12:00 PM', '10:00-12:00'],
    ['12:00 PM - 2:00 PM', '12:00-14:00'],
    ['2:00 PM - 4:00 PM', '14:00-16:00'],
    ['4:00 PM - 6:00 PM', '16:00-18:00']
  ].freeze

  def total_quantity
    purchasing_request_items.sum(:quantity)
  end

  def default_values
    self.approval_status ||= 'pending'
  end
end

app/controllers/purchasing_requests_controller.rb
class PurchasingRequestsController < ApplicationController
  before_action :set_purchasing_request, only: [:show, :edit, :update, :destroy, :delivered]
  before_action :set_suppliers, only: [:new, :create]

  def index
    @purchasing_requests = PurchasingRequest.all
  end

  def show
    @purchasing_request = PurchasingRequest.includes(:notes).find(params[:id])
    @all_purchasing_request_items = PurchasingRequestItem.all
    @note = Note.new
  end


  def new
    @purchasing_request = PurchasingRequest.new
    build_request_items
  end

  def create
    @purchasing_request = PurchasingRequest.new(purchasing_request_params)
    @purchasing_request.user = current_user
    @purchasing_request.approval_status = 'pending'
    if @purchasing_request.save
      # Notify the manager about the new request
      manager = User.find_by(position: 'manager')
      NewPurchaseRequest.with(purchasing_request: @purchasing_request).deliver(manager) if manager.present?
      redirect_to @purchasing_request, notice: 'Purchasing request was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @purchasing_request.update(purchasing_request_params)
      # Send notification
      manager = User.find_by(position: 'manager')
      notification_type = case @purchasing_request.approval_status
                          when 'approved'
                            PurchaseRequestApproved
                          when 'rejected'
                            PurchaseRequestRejected
                          when 'delivered'
                            PurchaseRequestDelivered
                          else
                            nil
                          end
      notification_type&.with(purchasing_request: @purchasing_request).deliver(manager) if manager.present?

      respond_to do |format|
        format.html { redirect_to @purchasing_request, notice: 'Purchasing request was successfully updated.' }
        format.turbo_stream
      end
    else
      format.html { render :show, status: :unprocessable_entity }
      format.turbo_stream
    end
  end

  def destroy
    @purchasing_request.destroy
    redirect_to purchasing_requests_path, notice: 'PR was successfully destroyed.'
  end

  def request_more_info
    @purchasing_request = PurchasingRequest.find(params[:id])
    if @purchasing_request.update(approval_status: 'pending', note: params[:request_more_info][:message])
      # Send notification to the manager
      manager = User.find_by(position: 'manager')
      PurchaseRequestMoreInfoNeeded.with(purchasing_request: @purchasing_request).deliver_later(manager)
      redirect_to @purchasing_request
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create_note
    @purchasing_request = PurchasingRequest.find(params[:id])
    @note = @purchasing_request.notes.new(note_params)
    @note.user = current_user
    respond_to do |format|
      if @note.save
        format.html { redirect_to @purchasing_request, notice: 'Note was successfully created.' }
        format.turbo_stream
      else
        format.html { render :show, status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end

  def create_comment
    @purchasing_request = PurchasingRequest.find(params[:id])
    @comment = @purchasing_request.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      # Send notification
      CommentNotification.with(comment: @comment).deliver(Manager.first)
      redirect_to @purchasing_request, notice: 'Comment was successfully created.'
    else
      # Handle comment creation failure
      render :show, status: :unprocessable_entity
    end
  end

  # def filter_wines
  #   supplier_id = params[:supplier_id]
  #   @wines = Wine.where(supplier_id: supplier_id)
  #   respond_to do |format|
  #     format.html { redirect_to new_purchasing_request_path }
  #     format.turbo_stream
  #   end
  # end

  private

  def more_info_params
    params.require(:more_info).permit(:message)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def note_params
    params.require(:note).permit(:content)
  end

  def set_purchasing_request
    @purchasing_request = PurchasingRequest.find(params[:id])
  end

  def set_suppliers
    @suppliers = Supplier.all.includes(:wines)
  end

  def build_request_items
    @suppliers.each do |supplier|
      supplier.wines.each do |wine|
        @purchasing_request.purchasing_request_items.build(wine: wine, quantity: 0)
      end
    end
  end

  def purchasing_request_params
    params.require(:purchasing_request).permit(:supplier_id, :delivery_date, :delivery_time_slot, :approval_status, :note, purchasing_request_items_attributes: [:id, :wine_id, :quantity])
  end
end

app/views/purchasing_requests/_approval_status.html.erb
<div class="row col-12">
  <p class="card-text col-6">Created By: <strong><%= purchasing_request.user.first_name %></strong>  (<%= current_user.position %>)</p>
  <p class="card-text col-6">Approval Status: <strong><%= purchasing_request.approval_status %></strong></p>
</div>

app/views/purchasing_requests/_buttons.html.erb
<div id="approval_buttons">
  <% if current_user.position == 'manager' && purchasing_request.approval_status == 'approved' %>
    <div class="row mb-2">
      <div class="col-12">
        <turbo-frame id="approval_buttons">
          <%= button_to 'Delivered', purchasing_request_path(purchasing_request, purchasing_request: { approval_status: 'delivered' }), method: :put, class: "btn-approve", data: { turbo_action: 'replace', turbo_frame: "approval_buttons" } %>
        </turbo-frame>
      </div>
    </div>
  <% elsif current_user.position == 'owner' %>
    <div class="row mb-2">
      <% if purchasing_request.approval_status == 'rejected' || purchasing_request.approval_status == 'pending' %>
        <div class="col-4">
          <turbo-frame id="approval_buttons">
            <%= button_to 'Approve', purchasing_request_path(purchasing_request, purchasing_request: { approval_status: 'approved' }), method: :put, class: "btn-approve", data: { turbo_action: 'replace', turbo_frame: "approval_buttons" } %>
          </turbo-frame>
        </div>
      <% end %>
      <% if purchasing_request.approval_status == 'approved' || purchasing_request.approval_status == 'pending' %>
        <div class="col-4">
          <turbo-frame id="approval_buttons">
            <%= button_to 'Reject', purchasing_request_path(purchasing_request, purchasing_request: { approval_status: 'rejected' }), method: :put, class: "btn-reject", data: { turbo_action: 'replace', turbo_frame: "approval_buttons" } %>
          </turbo-frame>
        </div>
      <% end %>
      <div class="col-4">
        <button type="button" class="btn-request" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Request More Info
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/purchasing_requests/_form.html.erb
<div class="container">
  <div class="row col-12 justify-content-center">
    <turbo-frame id="buttons_frame">
      <%= render partial: "purchasing_requests/buttons", locals: { purchasing_request: @purchasing_request } %>
    </turbo-frame>
  </div>
  <div class="row col-12">
    <turbo-frame id="approval_status_frame">
      <p class="card-text col-6">Approval Status: <strong><%= @purchasing_request.approval_status %></strong></p>
    </turbo-frame>
  </div>
</div>

app/views/purchasing_requests/create_note.turbo_stream.erb
<% if @note.persisted? %>
<%# add note to list %>
  <%= turbo_stream.prepend "notes" do %>
    <%= render partial: "notes/note", locals: { note: @note } %>
  <% end %>
  <%# replace form %>
  <%= turbo_stream.replace "new_note" do %>
    <%= render partial: "notes/form", locals: { note: Note.new, purchasing_request: @purchasing_request } %>
  <% end %>
  <% else %>
  <%= turbo_stream.replace "new_note" do %>
    <%= render partial: "notes/form", locals: { note: @note, purchasing_request: @purchasing_request } %>
  <% end %>

<% end %>

app/views/purchasing_requests/edit.html.erb
<body class="bg-color">
  <div class="container main-box">
    <h2 class="col-12 mb-3"><i class="fa fa-edit" aria-hidden="true"></i> Purchasing Request <%= @purchasing_request.id %></h2>
    <h4 class="col-12 mb-3 border-bottom pb-3"><%= @purchasing_request.supplier.name %></h4>
    <%= form_with(model: @purchasing_request, url: purchasing_request_path(@purchasing_request), method: :put, local: true, class: "form") do |form| %>
      <% if @purchasing_request.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@purchasing_request.errors.count, "error") %> prohibited this purchasing request from being updated:</h2>
        <ul>
          <% @purchasing_request.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

    <div class="row col-12">
      <div class="form-group col-6">
        <%= form.label :delivery_date %>
        <%= form.date_field :delivery_date, class: 'form-control' %>
      </div>

      <div class="form-group col-6">
        <%= form.label :delivery_time_slot %>
        <%= form.select :delivery_time_slot, options_for_select(PurchasingRequest::TIME_SLOTS), {prompt: "Select a time slot"}, { class: 'form-control' } %>
      </div>
    </div>
  </div>

    <div class="container main-box">
      <table class="table txt-s" id="wine_table">
        <thead  class="table-title py-3">
          <tr>
            <th>Maker</th>
            <th>Appellation</th>
            <th>Cuvee</th>
            <th>Vintage</th>
            <th style="width:60px">Qty</th>
          </tr>
        </thead>

      <tbody>
        <% @purchasing_request.supplier.wines.each do |wine| %>
          <tr class="wine-row">
            <td><%= wine.maker %></td>
            <td><%= wine.country %></td>
            <td><%= wine.vintage %></td>
            <td><%= wine.region %></td>
            <td>
              <%= form.fields_for :purchasing_request_items, @purchasing_request.purchasing_request_items.find_or_initialize_by(wine_id: wine.id) do |item| %>
                <%= item.hidden_field :wine_id, value: wine.id %>
                <%= item.number_field :quantity, value: item.object.quantity, min: 0, class: 'form-control', style: 'width: 100px;'%>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="form-group">
        <%= form.submit "Update", class: "btn-home btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</body>

app/views/purchasing_requests/error.js.erb
$("#note_errors").html("<%= j render 'shared/error_messages', object: @note %>");

app/views/purchasing_requests/index.html.erb
<body class="bg-color">
  <div class="container main-box mt-4">
    <div class="row col-12 mb-2">
      <h1 class="col-10">Purchasing Requests</h1>
      <div class="col-2 align-self-center"><%= link_to "Create PR", new_purchasing_request_path, class: "btn-create col-2 mb-3 mt-3" %></div>
    </div>
    <table class="table txt-s">
        <thead>
          <tr class="table-title">
            <th>#</th>
            <th>Creation Date</th>
            <th>Supplier</th>
            <th class="text-right">Delivery Date</th>
            <th class="text-right">Delivery Time</th>
            <th class="text-right">Quantities</th>
            <th class="text-center">Status</th>
          </tr>
        </thead>
        <tbody>
          <% @purchasing_requests.reverse_each do |pr| %>
              <tr data-controller="row-click" data-row-click-url="<%= purchasing_request_path(pr) %>" data-action="click->row-click#goToUrl">
                <td><%= pr.id %></td>
                <td><%= pr.created_at %></td>
                <td><%= pr.supplier.name %></td>
                <td class="text-right"><%= pr.delivery_date %></td>
                <td class="text-right"><%= pr.delivery_time_slot %></td>
                <td class="text-right"><%= pr.purchasing_request_items.map { |item| item.quantity if item.quantity && item.quantity > 0 }.compact.sum %></td>
                <td class="<%= pr.approval_status %> text-center"><%= pr.approval_status.capitalize %></td>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</body>

app/views/purchasing_requests/new.html.erb
  <script>
 document.addEventListener('turbo:load', function() {
    // Get the supplier select element
    let supplierSelect = document.querySelector('#supplier_select');

    // If the supplier select element exists
    if (supplierSelect) {
        // Hide all wine rows initially
        let wineRows = document.querySelectorAll('.wine-row');
        wineRows.forEach(function(row) {
            row.style.display = 'none';
        });

        // Add an event listener for the change event
        supplierSelect.addEventListener('change', function() {
            // Get the value of the selected supplier
            let selectedSupplierId = this.value;

            // Hide all wine rows initially
            wineRows.forEach(function(row) {
                row.style.display = 'none';
            });

            // Show wine rows for the selected supplier
            let selectedSupplierRows = document.querySelectorAll('.wine-row.supplier-' + selectedSupplierId);
            selectedSupplierRows.forEach(function(row) {
                row.style.display = 'table-row';
            });
        });
    }
});
  </script>

<body class="bg-color">
  <div class="container">
      <div class="row">
      <div class="row mt-4">
      <h2 class="col-11">New purchasing request</h2>
      <div class="col-1 align-self-center">
        <%= link_to "", purchasing_requests_path, class: "fas fa-arrow-left me-3" %>
      </div>
      <div class="container main-box col-12">
      <%= form_with(model: @purchasing_request, local: true, class: "form") do |form| %>
        <% if @purchasing_request.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(@purchasing_request.errors.count, "error") %> prohibited this purchasing request from being saved:</h2>

            <ul>
              <% @purchasing_request.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

      <div class="row col-12">
        <div class="form-group col-12">
          <%= form.label :supplier_id %>
          <%= form.collection_select :supplier_id, @suppliers, :id, :name, {prompt: "Select a supplier"}, { class: 'form-control', id: 'supplier_select' } %>
        </div>
      </div>

      <div class="row col-12">
        <div class="form-group col-6">
          <%= form.label :delivery_date %>
          <%= form.date_field :delivery_date, class: 'form-control' %>
        </div>

        <div class="form-group col-6">
          <%= form.label :delivery_time_slot %>
          <%= form.select :delivery_time_slot, options_for_select(PurchasingRequest::TIME_SLOTS), {prompt: "Select a time slot"}, { class: 'form-control' } %>
        </div>
      </div>

      <table class="table container txt-s" id="wine_table">
        <thead  class="table-title py-3">
          <tr>
            <th>Maker</th>
            <th>Appellation</th>
            <th>Cuvee</th>
            <th>Vintage</th>
            <th style="width:60px">Qty</th>
          </tr>
        </thead>

        <tbody>
          <% @suppliers.each do |supplier| %>
            <tr class="supplier-row" data-supplier-id="<%= supplier.id %>">
              <td colspan="6"><%= supplier.name %></td>
            </tr>
            <% supplier.wines.each do |wine| %>
              <tr class="wine-row supplier-<%= supplier.id %>">
                <td><%= wine.maker %></td>
                <td><%= wine.appellation %></td>
                <td><%= wine.cuvee %></td>
                <td><%= wine.vintage %></td>
                <td>
                  <%= form.fields_for :purchasing_request_items, @purchasing_request.purchasing_request_items.find_or_initialize_by(wine_id: wine.id) do |item| %>
                    <%= item.hidden_field :wine_id, value: wine.id %>
                    <%= item.number_field :quantity, value: item.object.quantity, min: 0, max: 100, class: 'form-control', style: 'width: 100px;' %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>

      <div class="form-group">
        <%= form.submit 'Create', class: 'btn-home col-12 mb-3' %>
      </div>
    <% end %>
  </div>
</body>

app/views/purchasing_requests/show.html.erb
<div class="container main-box mt-4">
  <body class="bg-color">
    <% if @purchasing_request.approval_status == 'delivered' %>
      <div class="alert alert-success" role="alert">
        Stock has been delivered!
      </div>
    <% end %>
    <div class="row">
      <h3 class="col-10">PR # <strong><%= @purchasing_request.id %></strong></h3><br>
        <div class="col-2">
        <%= link_to "", purchasing_requests_path, class: "fas fa-arrow-left mr-2" %>
        <%= link_to edit_purchasing_request_path(@purchasing_request), class: 'fas fa-edit icon-edit mr-2' do %>
        <% end %>
        <%= link_to purchasing_request_path(@purchasing_request), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this purchasing request?" }, class: 'fas fa-trash-alt icon-trash' do %>
        <% end %>
        </div>
      <div class="container col-12">
        <h5 class="border-bottom mb-3 pb-4"> <%= @purchasing_request.supplier.name %></h5>
      </div>
    </div>
    <!-- approval -->
    <div class="row col-12">
      <div class="card-text col-6">
        <strong>Created By:</strong> <%= @purchasing_request.user.first_name %>  (<%= current_user.position %>)
      </div>

      <turbo-frame id="approval_status_frame" class="card-text col-6">
        <strong>Approval Status:</strong> <%= @purchasing_request.approval_status %>
      </turbo-frame>
    </div>

    <div class="row col-12 mt-1">
      <div class="card-text col-6">
        <strong>Delivery Date:</strong> <%= @purchasing_request.delivery_date %>
      </div>
      <div class="card-text col-6">
        <strong>Delivery Time Slot:</strong> <%= @purchasing_request.delivery_time_slot %>
      </div>
    </div>

    <div class="row col-12 mt-1 txt-s">
      <div class="card-text col-6">
        <strong>Created on:</strong> <%= @purchasing_request.created_at.strftime("%A, %d %b %Y %l:%M %p") %>
      </div>
      <div class="card-text col-6">
        <strong>Updated on:</strong> <%= @purchasing_request.updated_at.strftime("%A, %d %b %Y %l:%M %p") %>
      </div>
    </div>



   <!-- Table -->
  <div class="container main-box mt-3">
    <h5>Order Details</h5>
    <table class="table mt-2 txt-s">
      <thead class="table-title">
        <tr>
          <th>Vint.</th>
          <th>Maker</th>
          <th>Appellation</th>
          <th>Cuvee</th>
          <th class="text-right">Selling price</th>
          <th class="text-right">Current stock</th>
          <th class="text-right">Unit price</th>
          <th class="text-right">Order Qty</th>
          <th class="text-right">Order Value</th>
        </tr>
      </thead>
      <tbody>
        <% @purchasing_request.purchasing_request_items.each do |item| %>
        <% if item.quantity && item.quantity > 0 %>
          <tr data-controller="wine-click" data-wine-click-url="<%= wine_path(item.wine) %>" data-action="click->wine-click#goToUrl">
            <td><%= item.wine.vintage %></td>
            <td><%= item.wine.maker %></td>
            <td><%= item.wine.appellation %></td>
            <td><%= item.wine.cuvee %></td>
            <td class="text-right">$<%= item.wine.selling_price %></td>
            <td class="text-right"><%= item.wine.quantity %></td>
            <td class="text-right">$<%= item.wine.unit_price %></td>
            <td class="text-right"><strong><%= item.quantity %></strong></td>
            <td class="text-right"><strong>$<%= item.quantity * item.wine.unit_price %></strong></td>
          </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
    <div class="row col-12 justify-content-center">
      <div class="col-4 total"><p>Total quantity: <strong><%= @purchasing_request.purchasing_request_items.inject(0) { |sum, item| sum + (item.quantity || 0) } %></strong></p></div>
      <div class="col-4 total"><p>Total value: <strong>$<%= @purchasing_request.purchasing_request_items.inject(0) { |sum, item| sum + (item.quantity || 0) * item.wine.unit_price } %></strong></p></div>
    </div>
  </div>
    <!-- approval buttons-->
    <div class="container">
      <div class="row col-12 justify-content-center">
        <turbo-frame id="buttons_frame">
          <%= render partial: "purchasing_requests/buttons", locals: { purchasing_request: @purchasing_request } %>
        </turbo-frame>
      </div>
    <!-- model-->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Request More Info</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <%= form_with(url: request_more_info_purchasing_request_path(@purchasing_request), method: :put, local: true) do |f| %>
                <div class="mb-3">
                  <%= f.label :message, "Message", class: "form-label" %>
                  <%= f.text_area :message, name: 'request_more_info[message]', class: "form-control" %>
                </div>
                <%= f.submit "Send", class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container main-box mt-2">
    <div class="card-body col-12">
      <!-- Display note if it exists -->
      <% if @purchasing_request.note.present? %>
      <h5 class="card-title border-bottom pb-3">Additional Information Requested</h5>
      <p class="card-text">※ <%= @purchasing_request.note %></p>
    </div>
    <% else %>
      <p><i>No note present for this request</i></p>
    <% end %>
  </div>

    <!-- Notes section -->
  <div class="container main-box mt-3">
    <div class="card-header table-title">
      <h5>Notes</h5>
    </div>
    <div class="card-body">
      <%= render partial: "notes/form", locals: { note: @note, purchasing_request: @purchasing_request } %>
      <div id="notes">
        <% @purchasing_request.notes.reverse_each do |note| %>
          <%= render partial: "notes/note", locals: { note: note } %>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/purchasing_requests/update.turbo_stream.erb
<% if @purchasing_request.errors.present? %>
  <%= turbo_stream.replace "purchasing_request_errors" do %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchasing_request.errors.count, "error") %> prohibited this purchasing_request from being saved:</h2>
      <ul>
        <% @purchasing_request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% else %>
  <%= turbo_stream.replace "approval_status_frame" do %>
    <p class="card-text col-6">Approval Status: <strong><%= @purchasing_request.approval_status %></strong></p>
  <% end %>

  <%= turbo_stream.replace "buttons_frame" do %>
    <%= render partial: "purchasing_requests/buttons", locals: { purchasing_request: @purchasing_request } %>
  <% end %>
<% end %>